version: "3.7"

services:
  mq:
    container_name: django_kick_start_mq
    image: rabbitmq:3-alpine

  db:
    container_name: django_kick_start_db
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  app:
    container_name: django_kick_start_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/DjangoKickstart
    environment:
      - DB_HOST=db
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=postgres
    depends_on:
      - db
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate --noinput &&
             python manage.py runserver 0.0.0.0:8000"

  celeryworker:
    container_name: django_kick_start_celery
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DISABLE_LOGGING=True
      - CELERY_BROKER_URL=amqp://mq:5672/
    command: celery -A project_name worker --loglevel=info
    depends_on:
      - mq
      - db
      - app